version: 2

updates:
    # Workflow files stored in the
    - package-ecosystem: "github-actions"
      commit-message:
          include: "scope"
          prefix: "github-actions"
        # default location of `.github/workflows`
      directory: "/"
      open-pull-requests-limit: 10
      schedule:
          interval: "daily"
