name: Tests

# Will run for every push on master and for every PR
on:
    push:
        branches: [ master ]
    pull_request:

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['7.2.0', '7.3.0', '7.4.0']
        name: PHP ${{ matrix.php-versions }} Test

        steps:
            - uses: actions/checkout@v2

            -   name: Validate composer.json and composer.lock
                run: composer validate

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress --no-suggest

            -   name: Docker setup
                run: docker run -d -p 7700:7700 getmeili/meilisearch:latest ./meilisearch --master-key=masterKey --no-analytics=true

            -   name: Run test suite
                run: composer test:unit

            -   name: Run linter
                run: composer lint:check
